default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: detect-private-key
      - id: end-of-file-fixer
        verbose: true
      - id: check-yaml

  - repo: local
    hooks:
      - id: go-unit-tests
        name: run go test s(go test)
        language: system
        entry: go test -v ./...
        pass_filenames: false
        types: [go]
        files: ^subdir/
        stages: [pre-commit]
